### ISSUE TITLE
Erros de Português no Módulo CDD [5 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#1]
O cliente está reclamando de possíveis erros de português no sistema no módulo de CDD. A principal reclamação está foca em diversos erros de português vindos dos textos de comunicação do software nas tabelas de Classificação Dewey.
image

**Comment by brunodiascultural** [comment]
O cliente está reclamando de possíveis erros de português no sistema no módulo de CDD. A principal reclamação está foca em diversos erros de português vindos dos textos de comunicação do software nas tabelas de Classificação Dewey.
image

**Comment by Rafafdev** [comment]
- [x] Ajustes de pontuação, letras maiúsculas e acentos onde necessário. (pagina classes.component.html)
- [x] Ajustes de pontuação, letras maiúsculas e acentos onde necessário. (pagina app-login.component.html)
- [x] Ajustes de pontuação, letras maiúsculas e acentos onde necessário. (pagina app-cadastro.component.html)
