### ISSUE TITLE
Serviço Biblioteconomia [10 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#12]
Monte um serviço que irá atender as informações que serão passadas para a interface de biblioteconomia com os modelos de cartões seguindo um padrão.

**Comment by MHideki78** [comment]
Criado endpoint no dia 27/01 criando uma nova branch no dia 01/02 para aprovação.

**Comment by brunodiascultural** [comment]
Finalizado!
