### ISSUE TITLE
Endpoint de Biblioteconomia [5 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#13]
Monte um json com as informações padronizadas para entrega para o serviço que atenderá a visualização do módulo de biblioteconomia. Também desenvolva a interface que padronize as informações para uso do serviço e do componente.

**Comment by MHideki78** [comment]
Criado endpoint no dia 27/01 criando uma nova branch no dia 01/02 para aprovação.

**Comment by brunodiascultural** [comment]
Finalizado!
