### ISSUE TITLE
Aplicar URL de Foto via Cadastro [25 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#14]
Criar um campo na criação do cadastro do usuário indicando um campo para colocar um endereço de imagem via URL para ser adicionado ao cadastro de autenticação de usuário.
Indicação para criação:

**Comment by SESSENO** [comment]
- [x] Criado campo no formulárioCadastro  para  inserção da URI com a foto. (app.cadastro.component.html).
- [x] Atualizado método enviaCadastro() para tratar variável url (app.cadastro.component.ts).
- [x] Alteração da função cadastrarUsuario, arquivo autenticacao-firebase.service.ts, a fim de tratar a entrada photoURL..

**Comment by brunodiascultural** [comment]
Atividade sem conflito.
