### ISSUE TITLE
Adição de Serviço de Login Google [25 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#15]
Adicione o método de autenticação com uso do Google Contas, a rotina é muito parecida com a de login de e-mail e senha. Porém deverá ser seguido a seguinte documentação:

Documentação do Firebase:
https://firebase.google.com/docs/auth/web/google-signin?hl=pt-br

Exemplo da chamada do recurso da nuvem:

**import { GoogleAuthProvider } from "firebase/auth";

const provider = new GoogleAuthProvider();**

**Comment by SESSENO** [comment]
- [x] Incluído botão com acionamento de evento (click) ao método loginUsuarioGgle(). Alterações no arquivo app-login.component.html.
- [x] Configurada pequena margem para melhor visualização do botão de login com a conta do Google. Alterações no arquivo app-login.component.scss.
- [x] Criado método loginUsuarioGgle() aplicando Toast para visualização do status do processo de login. Alterações no arquivo app-login.componente.ts
- [x]  Habilitação do serviço de login com conta Google no console do Firebase.  Houve necessidade de alteração das credenciais de acesso ao firebase, arquivos da pasta enviroments. O acesso disponibilizado não oferecia suporte a esse tipo de login.

**Comment by SESSENO** [comment]
- [x]  Alterados arquivos de ambiente (enviroments) abaixo. Devido à necessidade de utilização de conta Firebase do grupo, para efetuar os ajustes para o funcionamento do login Google.
> environment.prod.ts
> environment.ts

**Comment by SESSENO** [comment]
- [x] Criação do método loginUsuarioGoogle() utilizando a função signInWithPopup. Implementação no arquivo autenticacao-firebase.service.ts
