### ISSUE TITLE
Melhorias nos cartões do Feed [10 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#2]
Os sistemas de cartões tem a seguinte aparência, execute melhorias para deixar mais prática a visualização dos cartões para o usuário. Seja criativo e use comando SCSS e HTML e TS a vontade.
Estado atual dos cartões:
image.

**Comment by Rafafdev** [comment]
- [x] h1 centralizado na pagina feed.component.html. 
- [x] Mudança nos textos dos cards. (subtítulo, conteúdo) (pagina dashboard.json)
- [x] substituição de links para links onde leva o usuário direto na página de compra, onde ele pode avaliar o valor e a sinopse. (pagina dashboard.json)
- [x]  card 5 removido, para uma questão de estética.
- [x] Mudanças no card 4 para ficar na mesma estrutura do card 1 para ter uma variação de tamanhos.
- [x] Troca de icone (de informação para estrela) por uma questão de desing.
