### ISSUE TITLE
Serviço de Esquecer Senha [25 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#25]
Usando o serviço de Auth do Firebase monte uma rotina para recuperarmos a senha baseado nas rotinas de uso do Firebase Autenticação.

Link da documentação:
https://firebase.google.com/docs/auth/unity/manage-users?hl=pt-br#:~:text=Enviar%20um%20e%2Dmail%20de%20redefini%C3%A7%C3%A3o%20de%20senha,-Envie%20um%20e&text=e%2Dmail%22.-,Consulte%20Modelos%20de%20e%2Dmail%20na%20Central%20de%20Ajuda%20do,senha%20pelo%20Console%20do%20Firebase.

import { getAuth, sendPasswordResetEmail } from "firebase/auth";

const auth = getAuth();
sendPasswordResetEmail(auth, email)
.then(() => {
// Password reset email sent!
// ..
})
.catch((error) => {
const errorCode = error.code;
const errorMessage = error.message;
// ..
});

**Comment by SESSENO** [comment]
app-login.compomente.html
- [x]  Criado novo formulário (FormularioRecup);
- [x] Incluído botão para submit que aciona a função enviaEmailRecupSenha();

app-login.componente.ts

- [x] Criada a função enviaEmailRecupSenha()
> Inclusão de Toast para indicar Sucesso, Carregando ou Erros;
> Após execução encaminha para a rota [''];

autenticacao-firebase.service.ts
- [x] Criada a função emailRecupSenha(), utilizando a função do Firebase sendPassowrdRestEmail.
