### ISSUE TITLE
Endpoint de Psicologia [5 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#28]
Crie um json que será consumido pelo serviço de psicologia com as informações das 10 obras mais importantes de psicologia padronize as informações de modo que possa ser consumido pelo serviço com uma interface.

**Comment by MHideki78** [comment]
Criado endpoint no dia 27/01 criando uma nova branch no dia 01/02 para aprovação.

**Comment by brunodiascultural** [comment]
Finalizado!
