### ISSUE TITLE
Serviço de Psicologia [15 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#29]
Crie um serviço para consumidor os dados de um endpoint local para mostra-los em uma tabela. Utilize os padrões criados pela interface fornecida pelo endpoint. Adicionar ao serviço de navegação.

Menu Lateral

**Comment by MHideki78** [comment]
Criado endpoint no dia 27/01 criando uma nova branch no dia 01/02 para aprovação.

**Comment by brunodiascultural** [comment]
Finalizado!
