### ISSUE TITLE
Pagina de Psicologia [15 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#30]
Monte um componente com uma tabela consumindo um serviço que forneça as informações dos principais livros de psicologia. Adicione seu componente ao serviço de navegação.

**Comment by MHideki78** [comment]
Criado endpoint no dia 27/01 criando uma nova branch no dia 01/02 para aprovação.

**Comment by brunodiascultural** [comment]
Finalizado!
