### ISSUE TITLE
Pagina de Sugestões usando Grades [15 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#4]
Monte um componente que consuma uma API interna para sugestões de livros, ela deverá apresentar as sugestões em grades de dois ou três cartões usando a distribuição. Adicione seu componente ao serviço de navegação.

**Comment by MHideki78** [comment]
- [x] Criado Pagina de Sugestões no dia 27/01 criando uma nova branch no dia 31/01 para aprovação.
