### ISSUE TITLE
Serviço de Sugestões [10 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#5]
Montear um serviço o qual tenho formatação lógica para abastecer os dados dos cartões de sugestões consumindo a API local fornecida pela tarefa de endpoint. Editar o serviço de navegação para exibir via menu.

**Comment by MHideki78** [comment]
- [x] Criado serviços no dia 27/01 criando uma nova branch no dia 31/01 para aprovação.
