### ISSUE TITLE
Serviço de Tecnologia [10 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#51]
Crie um serviço que consuma os dados criados pelo json de tecnologia e padronizado para interface de tecnologia e os mostre em uma tabela e modele a exibição. Também adicione sua nova página ao serviço de navegação.

**Comment by MHideki78** [comment]
- [x] Estamos seguindo com a criação de dados pelo json para a inteface Tecnologia.
