### ISSUE TITLE
Endpoint de Sugestões [5 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#7]
Montar um sistema de endpoint local para ser consumido pelo sistema de serviço do componente de sugestões, também montar uma interface com o sistema de fornecimento das informações para ser consumido pelo serviço de sugestões.

Tarefas com referência: #60 #61 Todas estas tarefas fazem referência a este componente.

**Comment by MHideki78** [comment]
- [x] Criado endpoint no dia 27/01 criando uma nova branch no dia 31/01 para aprovação.
