### ISSUE TITLE
Serviço de Sagas [10 pts]

### ISSUE THREAD

**Issue by brunodiascultural** [brunodiascultural/bookshelf_v1#9]
Criar um serviço que atenda as demandas de informações para preencher os dados dos cartões do componente de sagas da literatura. Lembre-se de seguir a construção com o uso de informações dos endpoint.

**Comment by MHideki78** [comment]
Criado endpoint no dia 27/01 criando uma nova branch no dia 31/01 para aprovação.

**Comment by brunodiascultural** [comment]
Finalizado!
